# Generated by Django 4.2.13 on 2024-06-07 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='iteminfo',
            old_name='iten_name',
            new_name='item_name',
        ),
    ]
