# Generated by Django 4.2.13 on 2024-06-01 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_student_delete_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Student',
            new_name='User',
        ),
    ]
